services:
  postgres:
    image: postgres:16.4
    ports:
      - "5432:5432"
    volumes:
      - /usr/local/db-volumes/postgres-graby:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: infosoc


